export { capitalizeWords, capitalizeFirst } from './capitalizeText'
export { getProjectStatusConfig } from './getProjectStatusConfig'
export type { ProjectStatusConfig } from './getProjectStatusConfig'
export { getProposalStatusConfig } from './getProposalStatusConfig'
export type { ProposalStatusConfig } from './getProposalStatusConfig'
export { normalizeFileReference, normalizeFileReferences } from './fileUtils'
export type { NormalizedFileReference } from './fileUtils'
export { formatLocation } from './formatLocation'
export type { LocationObject } from './formatLocation'
