export { ProjectService } from './ProjectService'
export type { CreateProjectResult, ProjectData } from './ProjectService'
export { supabaseStorageService } from './SupabaseStorageService'
export type { SupabaseUploadResult, FileValidationResult, UploadOptions } from './SupabaseStorageService'
export { ProposalService, proposalService } from './ProposalService'
export type { CreateProposalResult, UpdateProposalResult } from './ProposalService'
